dist: focal # 20.04
language: python
services:
  - postgresql  # version 12 by default
python:
  - "3.7"
  - "3.8"
## Configure Oracle 11g R2 XE from https://github.com/Vincit/travis-oracledb-xe
## You will be able to connect the Oracle database in localhost:1521 with user/pass: travis/travis
## and with SYSDBA role user/pass: sys/travis.
sudo: required
env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE ORACLE_MAX_GESTOR_CONNECTIONS=20 ORACLE_GESTOR_POOL_TIMEOUT_MS=20000 ORACLE_STMT_TIMEOUT_MS=1500 ORACLE_SERVER=localhost ORACLE_PORT=1521 ORACLE_TABLESPACE=USERS ORACLE_USER=SYSTEM ORACLE_PASS=travis ORACLE_MAX_COLS=20 ORACLE_MAX_ROWS=1000 ORACLE_MAX_TABLES=20 PG_USER=postgres PG_PASS=travis PG_SERVER=localhost PG_PORT=5432 PG_DB=postgres
before_install:
  - sudo apt-get update
  - sudo apt install libaio1
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/u01/app/oracle/product/11.2.0/xe/lib
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
# Set a password for 'posgres' user
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'travis';" -U postgres
# command to run tests
script:
#  - ./pylint.sh
  - ./tests_travis.sh

